server:
  port: ${PORT:8080}
 
spring:
  application:
    name: api-gateway
 
info:
  name: api-gateway
  description: API Gateway Sample
  
zuul:
  add-host-header: true
  ignore-security-headers: false
  sensitiveHeaders:
  routes:
    security-server:
      path: /security/**
      serviceId: security-server
    aluno-service:
      path: /session/**
      serviceId: session-service
    disciplina-service:
      path: /speaker/**
      serviceId: speaker-service

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
   preferIpAddress: true