server:
  port: ${PORT:8082}
  
spring:
  application:
    name: conference-service
  
info:
  name: conference-service
  description: Conference Service Sample

security:
  sessions: stateless
  basic:
    enabled: false
  user:
    password: none    
  oauth2:
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo1jWPfjvJxaXCHzvClU7
            uJg+6AlZ8ht1Rbr+7Wo5o+YBWgCc6lZmSv/mwxvfL/wqagQ/W756a8vUJ7qFz/k9
            eBSJQSRuzJ6pT4OMMR9gbmYroh3RM/Xd5RelJgT3+OrvjAZr1pFYdAwp0q1T9XPa
            6PnCXq8KhIqNPxMjcaBrOycWEgWE4g4VnnrKDLtMmEZZIc0EMv8j7womsyNkbTyl
            nPsbFttNwtFoTVJeqvD01Fd6ISaoOVQAUfAcxvp77B/A1g0No3GHBupEtW3Hgp2/
            80Zl0+Gwjl6Wag5Mu9H7MIUPo+4xFGAJ0uwseHiErZqdWlHIo179IacB87+9Vt0g
            pwIDAQAB
            -----END PUBLIC KEY-----

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
   preferIpAddress: true