server:
  port: ${PORT:9999}

spring:
  application:
    name: security-server 

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
 instance:
   preferIpAddress: true